@baseUrl= http://localhost:5000/authors

GET {{baseUrl}}
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdXRob3JJZCI6IjY2ZGMzMDRhOTIxN2RlNDM4MDQ4ODM4NSIsImlhdCI6MTcyNTc4NzU1MiwiZXhwIjoxNzI1NzkxMTUyfQ.rUtK7KmC_m2_2FlaHT5NxJQiSyCbR4grYobXKZfgPBM

###

GET {{baseUrl}}/66c081c65a89916dbdae8b70
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdXRob3JJZCI6IjY2ZDJmYThlMmUxMzJlNWExNWI4Y2I4OCIsImlhdCI6MTcyNTU1NDY1MCwiZXhwIjoxNzI1NTU4MjUwfQ.Grwaj4q-x7Yb4rAqHTWJBFcR4DNUzqTC-5iUeycMqis


###

GET {{baseUrl}}/?perPage=4

###

POST {{baseUrl}}
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdXRob3JJZCI6IjY2ZDJmYThlMmUxMzJlNWExNWI4Y2I4OCIsImlhdCI6MTcyNTU1NDY1MCwiZXhwIjoxNzI1NTU4MjUwfQ.Grwaj4q-x7Yb4rAqHTWJBFcR4DNUzqTC-5iUeycMqis
Content-Type: application/json
 
{
    "name": "paolino",
      "surname": "paolinos",
      "email": "ferdinandos@gmail.com",
      "avatar": "",
      "password":"asdqwe"
} 

###

PUT {{baseUrl}}/66c1c346d5ecf93bca6c2ec9
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdXRob3JJZCI6IjY2ZDJmYThlMmUxMzJlNWExNWI4Y2I4OCIsImlhdCI6MTcyNTU1NDY1MCwiZXhwIjoxNzI1NTU4MjUwfQ.Grwaj4q-x7Yb4rAqHTWJBFcR4DNUzqTC-5iUeycMqis
Content-Type: application/json

{
    "name": "carlos",
    "surname": "carlettos",
    "email": "carlettos@gmail.com",
    "avatar": "carlos"
} 


###

DELETE {{baseUrl}}/66c081fb5a89916dbdae8b74
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdXRob3JJZCI6IjY2ZDJmYThlMmUxMzJlNWExNWI4Y2I4OCIsImlhdCI6MTcyNTU1NDY1MCwiZXhwIjoxNzI1NTU4MjUwfQ.Grwaj4q-x7Yb4rAqHTWJBFcR4DNUzqTC-5iUeycMqis

###



PATCH  {{baseUrl}}/66c62af62dd71a79a45ed7a9
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdXRob3JJZCI6IjY2ZDJmYThlMmUxMzJlNWExNWI4Y2I4OCIsImlhdCI6MTcyNTU1NDY1MCwiZXhwIjoxNzI1NTU4MjUwfQ.Grwaj4q-x7Yb4rAqHTWJBFcR4DNUzqTC-5iUeycMqis

{
    "avatar": "img.png"
} 
